---

- name: Deletion users
  no_log: true
  block:
    - name: Delete users
      ansible.builtin.uri:
        url: "{{ kctl_api_url }}"
        validate_certs: "{{ kctl_validate_certs }}"
        timeout: 600
        method: POST
        headers:
          Cookie: "{{ kctl_logon_response.cookies_string }}"
          X-Token: "{{ kctl_logon_response.json.result.token }}"
        body_format: json
        body: |
          {
            "jsonrpc":"2.0","id":1,"method":"Batch.run",
            "params":
              {
                "commandList":
                  [
                    {
                      "method":"Users.remove",
                      "params":
                        {
                          "userIds":{{ kctl_users_list_delete }},
                          "domainId":"{{ kctl_domain_id }}"
                        }
                    },
                    {
                      "method":"Session.getConfigTimestamp"
                    }
                  ]
              }
          }
      register: kctl_users_delete_response
      delegate_to: localhost

    - name: Collect API errors
      ansible.builtin.set_fact:
        kctl_api_error: "{{ kctl_api_error | default([]) +
          [{'kctl_api_error_task_name': 'Delete users',
              'kctl_api_error_msg': kctl_users_delete_response.json.error}] }}"
      when: kctl_users_delete_response.json.error is defined

    - name: Delete users - Timestamp list
      ansible.builtin.set_fact:
        kctl_timestamp_list_delete: "{{ kctl_timestamp_list_delete | default([]) + item.result.clientTimestampList }}"
      with_items: "{{ kctl_users_delete_response.json.result }}"
      when: item.result.clientTimestampList is defined

    - name: Delete users - Confirm config
      ansible.builtin.uri:
        url: "{{ kctl_api_url }}"
        validate_certs: "{{ kctl_validate_certs }}"
        timeout: 600
        method: POST
        headers:
          Cookie: "{{ kctl_logon_response.cookies_string }}"
          X-Token: "{{ kctl_logon_response.json.result.token }}"
        body_format: json
        body: |
          {
            "jsonrpc":"2.0","id":1,"method":"Session.confirmConfig",
            "params":
              {
                "clientTimestampList":{{ kctl_timestamp_list_delete }}
              }
          }
      register: kctl_confirmation_delete
      delegate_to: localhost

    - name: Collect API errors
      ansible.builtin.set_fact:
        kctl_api_error: "{{ kctl_api_error | default([]) +
          [{'kctl_api_error_task_name': 'Delete users - Confirm Config',
              'kctl_api_error_msg': kctl_confirmation_delete.json.error}] }}"
      when: kctl_confirmation_delete.json.error is defined
  rescue:
    - name: Collect task errors
      ansible.builtin.set_fact:
        kctl_task_errors: "{{ kctl_task_errors | default([]) +
          [{'kctl_error_task_name': ansible_failed_task.name, 'kctl_error_task_msg': ansible_failed_result.msg}] }}"

...
