---

- name: Get Users
  ansible.builtin.uri:
    url: "{{ kctl_api_url }}"
    validate_certs: "{{ kctl_validate_certs }}"
    timeout: 600
    method: POST
    headers:
      Cookie: "{{ kctl_logon_response.cookies_string }}"
      X-Token: "{{ kctl_logon_response.json.result.token }}"
    body_format: json
    body: |
      {
        "jsonrpc":"2.0","id":1,"method":"Users.get",
        "params":
          {
            "query":
              {
                "start":0,
                "limit":-1,
                "orderBy":[{"columnName":"userName","direction":"Asc"}]
              },
            "domainId":"{{ kctl_domain_id }}"
          }
      }
  register: kctl_users_get_response
  no_log: true
  delegate_to: localhost

...
