---
# tasks file for kctl_users

- name: Set start timestamp
  ansible.builtin.set_fact:
    kctl_users_start_timestamp: "{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }} (UTC)"

- name: Login to a Kerio Control API
  ansible.builtin.include_tasks:
    file: api_login.yml

- name: Get Users
  ansible.builtin.include_tasks:
    file: get_users.yml

- name: Render users lists
  ansible.builtin.include_tasks:
    file: render_users_lists.yml

- name: Delete users
  ansible.builtin.include_tasks:
    file: delete_users.yml
  when: kctl_users_list_delete is defined

- name: Update users
  ansible.builtin.include_tasks:
    file: update_users.yml
  when: kctl_users_list_update is defined

- name: Create users
  ansible.builtin.include_tasks:
    file: create_users.yml
  when: kctl_users_list_create is defined

- name: Set end timestamp
  ansible.builtin.set_fact:
    kctl_users_end_timestamp: "{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }} (UTC)"

- name: Render report
  ansible.builtin.include_tasks:
    file: render_report.yml

- name: Logout
  ansible.builtin.include_tasks:
    file: api_logout.yml

- name: Report
  ansible.builtin.include_tasks:
    file: report.yml

...
